In [9]:
import numpy as np
import pandas as pd

In [7]:
%ls

 Canada.xlsx            README.md          session_01/   session_10/
'clase 4 pivot.ipynb'   requierementsEXL   session_07/   Untitled.ipynb
 datasets/              requirements.txt   session_08/   welcome_binder.ipynb
 nhanes_2015_2016.csv   runtime.txt        session_09/

In [12]:
df = pd.read_csv('datasets/census.csv')

In [13]:
df

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43593,...,1.072643,16.243199,-5.339774,-14.252889,-14.248864,1.255221,16.243199,-5.295460,-14.075283,-14.070195
3189,50,4,8,56,39,Wyoming,Teton County,21294,21294,21297,...,-1.589565,0.972695,19.525929,14.143021,-0.564849,0.654527,2.408578,21.160658,16.308671,1.520747
3190,50,4,8,56,41,Wyoming,Uinta County,21118,21118,21102,...,-17.755986,-4.916350,-6.902954,-14.215862,-12.127022,-18.136812,-5.536861,-7.521840,-14.740608,-12.606351
3191,50,4,8,56,43,Wyoming,Washakie County,8533,8533,8545,...,-11.637475,-0.827815,-2.013502,-17.781491,1.682288,-11.990126,-1.182592,-2.250385,-18.020168,1.441961
3192,50,4,8,56,45,Wyoming,Weston County,7208,7208,7181,...,-11.752361,-8.040059,12.372583,1.533635,6.935294,-12.032179,-8.040059,12.372583,1.533635,6.935294

In [15]:
df.head(2)

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333

In [16]:
df.pivot_table(df,
              index = 'STNAME')

,BIRTHS2010,BIRTHS2011,BIRTHS2012,BIRTHS2013,BIRTHS2014,BIRTHS2015,CENSUS2010POP,COUNTY,DEATHS2010,DEATHS2011,...,RNATURALINC2013,RNATURALINC2014,RNATURALINC2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,STATE,SUMLEV
STNAME,,,,,,,,,,,,,,,,,,,,,
Alabama,418.411765,1755.558824,1737.117647,1704.058824,1715.705882,1714.852941,1.405805e+05,66.014706,326.147059,1435.617647,...,-0.409414,0.054710,-0.100651,-2.725005,-2.292901,-1.463650,-0.905197,-1.128223,1,49.852941
Alaska,192.800000,780.733333,741.733333,756.533333,764.133333,766.533333,4.734873e+04,144.666667,61.200000,261.866667,...,8.891992,8.527192,7.925742,2.134501,-1.536076,-5.627717,-14.085226,-9.051064,2,49.666667
Arizona,2617.125000,10763.000000,10695.750000,10762.875000,10819.500000,10923.125000,7.990021e+05,13.000000,1436.125000,6019.000000,...,3.793521,3.976337,3.898476,1.771913,-0.023229,-0.596425,3.924205,1.641436,4,49.375000
Arkansas,248.394737,1011.710526,1015.894737,999.447368,997.684211,995.263158,7.673468e+04,74.013158,184.815789,774.394737,...,-0.417358,0.493069,0.181553,-2.012963,-4.440494,-3.770100,-4.920219,-3.762177,5,49.868421
California,4180.474576,17280.237288,16862.067797,16936.169492,16935.016949,17079.627119,1.262846e+06,57.016949,1941.830508,8083.593220,...,3.756396,3.822479,3.878222,-2.090790,-1.713330,-1.217442,0.523891,1.811619,6,49.830508
Colorado,516.646154,2028.184615,1992.000000,1991.969231,2035.661538,2063.292308,1.547445e+05,61.276923,241.723077,984.769231,...,2.461998,3.529490,3.157664,-2.172311,-3.836376,1.505679,1.782417,6.467947,8,49.846154
Connecticut,2108.666667,8363.555556,8188.666667,8029.777778,8040.444444,8050.000000,7.942438e+05,7.111111,1518.666667,6515.777778,...,1.029969,1.123078,1.170321,-0.366813,-2.782544,-1.283525,-3.388320,-2.966487,9,48.888889
Delaware,1423.500000,5649.500000,5579.000000,5445.000000,5463.500000,5516.500000,4.489670e+05,2.250000,921.000000,3937.500000,...,2.669687,2.558482,2.351574,6.750610,8.091576,7.725541,10.138992,9.844298,10,47.500000
District of Columbia,2243.000000,9196.000000,9234.000000,9447.000000,9415.000000,9593.000000,6.017230e+05,0.500000,1180.000000,4671.000000,...,7.219340,6.697847,6.568753,17.028422,15.972111,15.634120,8.378037,12.434838,11,45.000000
Florida,1496.235294,6271.088235,6295.176471,6264.823529,6414.352941,6489.058824,5.529797e+05,66.911765,1229.117647,5132.470588,...,-0.105908,0.105289,0.033415,3.470416,5.326840,7.375903,10.138389,13.844303,12,49.852941
Georgia,406.112500,1657.687500,1648.587500,1608.412500,1621.525000,1632.400000,1.210957e+05,160.481250,215.025000,888.462500,...,2.108193,2.591647,2.208116,-2.836543,-3.621045,-2.891501,-0.631554,1.593557,13,49.937500
Hawaii,1548.666667,6384.333333,6297.000000,6345.666667,6340.333333,6432.666667,4.534337e+05,4.166667,844.000000,3361.333333,...,4.695644,3.988016,3.985757,3.648422,3.913394,6.177927,5.706001,3.720997,15,48.333333
Idaho,265.377778,1020.222222,993.955556,1009.111111,999.422222,1011.155556,6.967031e+04,43.022222,114.266667,528.177778,...,4.392427,4.810836,5.227073,-7.854248,-8.825121,-4.097757,-1.488222,0.690367,16,49.777778
Illinois,812.349515,3153.922330,3109.514563,3058.446602,3046.854369,3037.669903,2.491385e+05,101.009709,467.223301,1973.067961,...,-0.160432,0.592989,0.521138,-2.883061,-5.210972,-4.832850,-5.534991,-5.688735,17,49.902913
Indiana,450.774194,1794.774194,1786.236559,1793.032258,1791.053763,1802.064516,1.394366e+05,91.010753,298.258065,1244.989247,...,1.542413,2.057171,2.232014,-1.897948,-2.909838,-0.913553,-1.338054,-2.157711,18,49.892473
Iowa,199.340000,757.120000,769.420000,776.100000,787.320000,789.400000,6.092710e+04,98.010000,137.400000,564.140000,...,0.190352,1.249341,1.302347,-1.740608,-3.606876,-1.572610,-1.625015,-2.687377,19,49.900000
Kansas,188.528302,756.943396,746.981132,749.358491,735.000000,734.981132,5.383242e+04,104.009434,113.113208,475.037736,...,0.988300,2.222274,2.479288,-3.106460,-3.856868,-2.593956,-6.297516,-6.844159,20,49.905660
Kentucky,226.297521,914.264463,914.016529,926.264463,915.752066,920.512397,7.172507e+04,119.008264,174.000000,703.024793,...,0.528409,1.063336,0.963612,0.519852,-3.120999,-1.973509,-1.282231,-0.883223,21,49.917355
Louisiana,448.400000,1917.415385,1915.784615,1924.030769,1956.400000,1954.307692,1.394884e+05,63.015385,282.584615,1254.000000,...,2.455995,3.279455,3.023136,-2.723966,-2.853650,-2.987906,-3.058349,-3.000496,22,49.846154
Maine,405.058824,1486.000000,1506.000000,1513.411765,1497.882353,1510.235294,1.562778e+05,15.058824,364.588235,1533.176471,...,-1.291828,-1.299046,-1.258894,0.028492,-0.346601,-0.815261,-0.233754,-0.865096,23,49.411765
Maryland,1476.880000,5883.280000,5816.960000,5788.880000,5785.760000,5820.320000,4.618842e+05,43.160000,850.400000,3493.040000,...,2.250770,1.836974,1.873135,3.396201,0.420937,1.409956,0.615701,0.833938,24,49.600000
Massachusetts,2486.266667,9758.000000,9627.733333,9622.000000,9657.333333,9747.200000,8.730172e+05,13.066667,1638.933333,7202.133333,...,1.651614,1.584702,1.701269,3.047456,3.433998,5.116174,4.833723,1.741375,25,49.333333
Michigan,692.904762,2713.904762,2692.380952,2690.666667,2717.809524,2726.690476,2.353248e+05,82.011905,527.261905,2139.833333,...,-1.002665,-0.879799,-0.683298,-1.179993,-2.382996,-0.700194,0.131114,-1.238100,26,49.880952
Minnesota,397.727273,1553.909091,1546.795455,1567.318182,1583.818182,1587.545455,1.205438e+05,86.011364,212.386364,908.681818,...,1.716511,2.532826,2.594118,-1.459704,-4.546701,-1.281099,-2.234970,-1.689923,27,49.886364
Mississippi,227.012048,957.614458,949.903614,927.373494,929.469880,928.867470,7.150113e+04,81.012048,160.120482,701.903614,...,1.477254,2.012264,1.951839,-6.372714,-5.095254,-3.437371,-4.967510,-6.574590,28,49.879518
Missouri,327.793103,1314.448276,1300.500000,1296.137931,1304.189655,1302.741379,1.032574e+05,116.698276,227.224138,965.103448,...,0.510463,1.095863,1.086833,-2.481754,-3.702700,-1.915292,-1.745257,-2.171529,29,49.913793
Montana,107.649123,421.017544,422.350877,428.315789,439.298246,441.859649,3.471632e+04,55.017544,83.824561,320.175439,...,0.401270,1.781828,2.153718,2.731017,6.706740,5.837909,-0.087574,0.336274,30,49.824561
Nebraska,138.617021,547.446809,548.212766,553.617021,556.319149,558.638298,3.885832e+04,92.010638,77.787234,332.340426,...,0.080261,2.371397,2.372432,-3.421450,-3.999059,-3.985326,-4.878224,-2.538840,31,49.893617
Nevada,988.000000,3983.000000,3856.555556,3899.111111,3931.111111,4004.000000,3.000612e+05,43.000000,549.444444,2243.666667,...,-0.106740,2.210785,2.695376,-7.508344,6.008135,8.769259,-5.590689,-0.182868,32,49.444444
New Hampshire,594.363636,2362.363636,2248.909091,2290.363636,2239.818182,2284.000000,2.393582e+05,9.090909,458.000000,1952.000000,...,-0.209383,-0.448162,-0.285521,-1.036917,-0.210224,-0.373640,2.542750,-0.084044,33,49.090909
New Jersey,2411.727273,9698.545455,9501.454545,9405.636364,9335.454545,9364.181818,7.992631e+05,20.045455,1554.909091,6460.363636,...,2.558580,2.555374,2.506701,-0.580628,-1.536388,-1.134388,-0.699767,-2.252911,34,49.545455
New Mexico,391.117647,1635.470588,1590.470588,1572.470588,1547.000000,1546.235294,1.211282e+05,29.264706,224.117647,963.176471,...,2.006790,2.758092,2.748721,-1.136810,-7.440323,-7.322115,-11.949971,-5.589307,35,49.705882
New York,1949.650794,7718.031746,7616.603175,7615.015873,7522.730159,7581.936508,6.151778e+05,61.015873,1115.365079,4753.619048,...,1.409451,1.445406,1.394635,-0.697907,-2.468041,-2.639574,-3.748221,-4.038662,36,49.841270
North Carolina,592.356436,2396.891089,2367.663366,2364.059406,2374.772277,2389.623762,1.888214e+05,99.009901,369.900990,1582.930693,...,0.413886,0.715104,0.565011,1.289216,-0.292988,1.960016,1.831665,2.313254,37,49.900990
North Dakota,86.703704,340.629630,365.740741,379.592593,404.925926,413.703704,2.491078e+04,52.018519,55.296296,224.222222,...,1.403685,3.531502,3.955410,10.178562,17.685400,16.293701,5.143137,7.717923,38,49.814815
Ohio,782.224719,3099.662921,3094.224719,3125.662921,3127.101124,3143.460674,2.592473e+05,87.011236,594.696629,2487.820225,...,1.130594,1.343825,1.418471,-1.953373,-3.731664,-2.004723,-1.516972,-2.221428,39,49.887640
Oklahoma,337.025641,1347.564103,1342.333333,1367.794872,1373.000000,1383.743590,9.618849e+04,76.012821,209.589744,965.102564,...,1.267738,2.062214,1.966682,1.167865,-0.190687,2.586180,-0.491743,-0.441090,40,49.871795
Oregon,642.000000,2453.783784,2427.621622,2432.702703,2465.027027,2491.405405,2.070851e+05,35.027027,420.216216,1758.756757,...,0.782994,1.147373,1.154022,0.777475,0.376182,0.554408,2.838808,6.558683,41,49.729730
Pennsylvania,1061.794118,4204.617647,4179.882353,4171.411765,4162.029412,4175.176471,3.735994e+05,66.014706,886.235294,3757.794118,...,-0.716604,-0.506350,-0.505196,0.603322,-0.251711,-1.792030,-1.163071,-1.847809,42,49.852941
Rhode Island,958.333333,3668.000000,3670.000000,3623.333333,3609.000000,3661.333333,3.508557e+05,4.166667,778.333333,3254.333333,...,-0.170788,-0.484658,-0.230390,-3.775228,-1.048551,-0.204570,1.137026,0.723810,44,48.333333
South Carolina,603.404255,2445.617021,2447.744681,2407.404255,2444.595745,2464.042553,1.968240e+05,45.021277,412.085106,1788.595745,...,0.659936,0.850789,0.678485,-1.472263,-0.306189,1.327016,3.492896,2.782227,45,49.787234
South Dakota,90.507463,351.850746,354.955224,359.611940,371.134328,368.477612,2.430388e+04,66.940299,57.552239,217.701493,...,2.666053,5.298887,5.033705,1.911915,1.439128,0.736253,-5.302795,-4.119402,46,49.850746
Tennessee,409.645833,1637.833333,1673.020833,1672.291667,1673.958333,1692.937500,1.322105e+05,94.010417,298.229167,1254.187500,...,-0.600753,-0.350063,0.003528,1.126826,2.052995,2.309163,4.114514,3.222675,47,49.895833
Texas,727.584314,2994.086275,2965.662745,3015.003922,3081.513725,3122.258824,1.972201e+05,253.003922,320.721569,1318.086275,...,2.307281,3.652447,3.961225,0.596987,-0.318782,2.231198,0.294187,5.312238,48,49.960784
Utah,916.800000,3461.000000,3363.066667,3457.200000,3396.066667,3434.400000,1.842590e+05,28.033333,246.400000,1000.133333,...,8.617214,8.809143,9.165748,0.118982,-5.076607,2.873422,-0.323116,3.945287,49,49.666667
Vermont,220.533333,806.933333,812.266667,796.266667,795.333333,797.466667,8.343213e+04,13.066667,177.200000,724.133333,...,0.067339,0.211974,0.507417,0.173740,-2.423507,0.078297,-1.853272,-2.161046,50,49.333333
Virginia,383.850746,1527.268657,1533.820896,1529.791045,1534.104478,1542.641791,1.193718e+05,262.022388,219.149254,902.089552,...,0.403384,1.167868,1.056480,1.425543,1.554178,2.106060,1.113487,1.428749,51,49.925373
Washington,1112.200000,4335.150000,4335.700000,4362.200000,4374.550000,4439.100000,3.362270e+05,38.025000,591.500000,2491.700000,...,2.532388,2.412320,2.524687,4.071678,1.142338,1.740031,3.845933,7.155971,53,49.750000
West Virginia,182.285714,730.785714,738.500000,747.642857,739.464286,741.571429,6.617836e+04,54.017857,186.964286,782.500000,...,-1.514972,-1.185371,-1.212872,0.165489,-0.709094,-1.979607,-3.144217,-2.635547,54,49.821429
Wisconsin,481.041096,1857.315068,1853.287671,1832.602740,1825.424658,1831.753425,1.558078e+05,70.123288,321.780822,1328.438356,...,0.675113,1.047348,1.211926,0.336399,-3.125900,-0.289083,-0.544351,-1.739969,55,49.863014
Wyoming,166.250000,622.583333,619.500000,625.750000,646.500000,641.250000,4.696883e+04,22.041667,107.750000,370.583333,...,3.599852,4.587221,4.167062,-1.468521,5.328961,4.388464,-4.710593,-1.858504,56,49.583333

In [17]:
df.pivot_table(df,
              index = 'STNAME')

,BIRTHS2010,BIRTHS2011,BIRTHS2012,BIRTHS2013,BIRTHS2014,BIRTHS2015,CENSUS2010POP,COUNTY,DEATHS2010,DEATHS2011,...,RNATURALINC2013,RNATURALINC2014,RNATURALINC2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,STATE,SUMLEV
STNAME,,,,,,,,,,,,,,,,,,,,,
Alabama,418.411765,1755.558824,1737.117647,1704.058824,1715.705882,1714.852941,1.405805e+05,66.014706,326.147059,1435.617647,...,-0.409414,0.054710,-0.100651,-2.725005,-2.292901,-1.463650,-0.905197,-1.128223,1,49.852941
Alaska,192.800000,780.733333,741.733333,756.533333,764.133333,766.533333,4.734873e+04,144.666667,61.200000,261.866667,...,8.891992,8.527192,7.925742,2.134501,-1.536076,-5.627717,-14.085226,-9.051064,2,49.666667
Arizona,2617.125000,10763.000000,10695.750000,10762.875000,10819.500000,10923.125000,7.990021e+05,13.000000,1436.125000,6019.000000,...,3.793521,3.976337,3.898476,1.771913,-0.023229,-0.596425,3.924205,1.641436,4,49.375000
Arkansas,248.394737,1011.710526,1015.894737,999.447368,997.684211,995.263158,7.673468e+04,74.013158,184.815789,774.394737,...,-0.417358,0.493069,0.181553,-2.012963,-4.440494,-3.770100,-4.920219,-3.762177,5,49.868421
California,4180.474576,17280.237288,16862.067797,16936.169492,16935.016949,17079.627119,1.262846e+06,57.016949,1941.830508,8083.593220,...,3.756396,3.822479,3.878222,-2.090790,-1.713330,-1.217442,0.523891,1.811619,6,49.830508
Colorado,516.646154,2028.184615,1992.000000,1991.969231,2035.661538,2063.292308,1.547445e+05,61.276923,241.723077,984.769231,...,2.461998,3.529490,3.157664,-2.172311,-3.836376,1.505679,1.782417,6.467947,8,49.846154
Connecticut,2108.666667,8363.555556,8188.666667,8029.777778,8040.444444,8050.000000,7.942438e+05,7.111111,1518.666667,6515.777778,...,1.029969,1.123078,1.170321,-0.366813,-2.782544,-1.283525,-3.388320,-2.966487,9,48.888889
Delaware,1423.500000,5649.500000,5579.000000,5445.000000,5463.500000,5516.500000,4.489670e+05,2.250000,921.000000,3937.500000,...,2.669687,2.558482,2.351574,6.750610,8.091576,7.725541,10.138992,9.844298,10,47.500000
District of Columbia,2243.000000,9196.000000,9234.000000,9447.000000,9415.000000,9593.000000,6.017230e+05,0.500000,1180.000000,4671.000000,...,7.219340,6.697847,6.568753,17.028422,15.972111,15.634120,8.378037,12.434838,11,45.000000
Florida,1496.235294,6271.088235,6295.176471,6264.823529,6414.352941,6489.058824,5.529797e+05,66.911765,1229.117647,5132.470588,...,-0.105908,0.105289,0.033415,3.470416,5.326840,7.375903,10.138389,13.844303,12,49.852941
Georgia,406.112500,1657.687500,1648.587500,1608.412500,1621.525000,1632.400000,1.210957e+05,160.481250,215.025000,888.462500,...,2.108193,2.591647,2.208116,-2.836543,-3.621045,-2.891501,-0.631554,1.593557,13,49.937500
Hawaii,1548.666667,6384.333333,6297.000000,6345.666667,6340.333333,6432.666667,4.534337e+05,4.166667,844.000000,3361.333333,...,4.695644,3.988016,3.985757,3.648422,3.913394,6.177927,5.706001,3.720997,15,48.333333
Idaho,265.377778,1020.222222,993.955556,1009.111111,999.422222,1011.155556,6.967031e+04,43.022222,114.266667,528.177778,...,4.392427,4.810836,5.227073,-7.854248,-8.825121,-4.097757,-1.488222,0.690367,16,49.777778
Illinois,812.349515,3153.922330,3109.514563,3058.446602,3046.854369,3037.669903,2.491385e+05,101.009709,467.223301,1973.067961,...,-0.160432,0.592989,0.521138,-2.883061,-5.210972,-4.832850,-5.534991,-5.688735,17,49.902913
Indiana,450.774194,1794.774194,1786.236559,1793.032258,1791.053763,1802.064516,1.394366e+05,91.010753,298.258065,1244.989247,...,1.542413,2.057171,2.232014,-1.897948,-2.909838,-0.913553,-1.338054,-2.157711,18,49.892473
Iowa,199.340000,757.120000,769.420000,776.100000,787.320000,789.400000,6.092710e+04,98.010000,137.400000,564.140000,...,0.190352,1.249341,1.302347,-1.740608,-3.606876,-1.572610,-1.625015,-2.687377,19,49.900000
Kansas,188.528302,756.943396,746.981132,749.358491,735.000000,734.981132,5.383242e+04,104.009434,113.113208,475.037736,...,0.988300,2.222274,2.479288,-3.106460,-3.856868,-2.593956,-6.297516,-6.844159,20,49.905660
Kentucky,226.297521,914.264463,914.016529,926.264463,915.752066,920.512397,7.172507e+04,119.008264,174.000000,703.024793,...,0.528409,1.063336,0.963612,0.519852,-3.120999,-1.973509,-1.282231,-0.883223,21,49.917355
Louisiana,448.400000,1917.415385,1915.784615,1924.030769,1956.400000,1954.307692,1.394884e+05,63.015385,282.584615,1254.000000,...,2.455995,3.279455,3.023136,-2.723966,-2.853650,-2.987906,-3.058349,-3.000496,22,49.846154
Maine,405.058824,1486.000000,1506.000000,1513.411765,1497.882353,1510.235294,1.562778e+05,15.058824,364.588235,1533.176471,...,-1.291828,-1.299046,-1.258894,0.028492,-0.346601,-0.815261,-0.233754,-0.865096,23,49.411765
Maryland,1476.880000,5883.280000,5816.960000,5788.880000,5785.760000,5820.320000,4.618842e+05,43.160000,850.400000,3493.040000,...,2.250770,1.836974,1.873135,3.396201,0.420937,1.409956,0.615701,0.833938,24,49.600000
Massachusetts,2486.266667,9758.000000,9627.733333,9622.000000,9657.333333,9747.200000,8.730172e+05,13.066667,1638.933333,7202.133333,...,1.651614,1.584702,1.701269,3.047456,3.433998,5.116174,4.833723,1.741375,25,49.333333
Michigan,692.904762,2713.904762,2692.380952,2690.666667,2717.809524,2726.690476,2.353248e+05,82.011905,527.261905,2139.833333,...,-1.002665,-0.879799,-0.683298,-1.179993,-2.382996,-0.700194,0.131114,-1.238100,26,49.880952
Minnesota,397.727273,1553.909091,1546.795455,1567.318182,1583.818182,1587.545455,1.205438e+05,86.011364,212.386364,908.681818,...,1.716511,2.532826,2.594118,-1.459704,-4.546701,-1.281099,-2.234970,-1.689923,27,49.886364
Mississippi,227.012048,957.614458,949.903614,927.373494,929.469880,928.867470,7.150113e+04,81.012048,160.120482,701.903614,...,1.477254,2.012264,1.951839,-6.372714,-5.095254,-3.437371,-4.967510,-6.574590,28,49.879518
Missouri,327.793103,1314.448276,1300.500000,1296.137931,1304.189655,1302.741379,1.032574e+05,116.698276,227.224138,965.103448,...,0.510463,1.095863,1.086833,-2.481754,-3.702700,-1.915292,-1.745257,-2.171529,29,49.913793
Montana,107.649123,421.017544,422.350877,428.315789,439.298246,441.859649,3.471632e+04,55.017544,83.824561,320.175439,...,0.401270,1.781828,2.153718,2.731017,6.706740,5.837909,-0.087574,0.336274,30,49.824561
Nebraska,138.617021,547.446809,548.212766,553.617021,556.319149,558.638298,3.885832e+04,92.010638,77.787234,332.340426,...,0.080261,2.371397,2.372432,-3.421450,-3.999059,-3.985326,-4.878224,-2.538840,31,49.893617
Nevada,988.000000,3983.000000,3856.555556,3899.111111,3931.111111,4004.000000,3.000612e+05,43.000000,549.444444,2243.666667,...,-0.106740,2.210785,2.695376,-7.508344,6.008135,8.769259,-5.590689,-0.182868,32,49.444444
New Hampshire,594.363636,2362.363636,2248.909091,2290.363636,2239.818182,2284.000000,2.393582e+05,9.090909,458.000000,1952.000000,...,-0.209383,-0.448162,-0.285521,-1.036917,-0.210224,-0.373640,2.542750,-0.084044,33,49.090909
New Jersey,2411.727273,9698.545455,9501.454545,9405.636364,9335.454545,9364.181818,7.992631e+05,20.045455,1554.909091,6460.363636,...,2.558580,2.555374,2.506701,-0.580628,-1.536388,-1.134388,-0.699767,-2.252911,34,49.545455
New Mexico,391.117647,1635.470588,1590.470588,1572.470588,1547.000000,1546.235294,1.211282e+05,29.264706,224.117647,963.176471,...,2.006790,2.758092,2.748721,-1.136810,-7.440323,-7.322115,-11.949971,-5.589307,35,49.705882
New York,1949.650794,7718.031746,7616.603175,7615.015873,7522.730159,7581.936508,6.151778e+05,61.015873,1115.365079,4753.619048,...,1.409451,1.445406,1.394635,-0.697907,-2.468041,-2.639574,-3.748221,-4.038662,36,49.841270
North Carolina,592.356436,2396.891089,2367.663366,2364.059406,2374.772277,2389.623762,1.888214e+05,99.009901,369.900990,1582.930693,...,0.413886,0.715104,0.565011,1.289216,-0.292988,1.960016,1.831665,2.313254,37,49.900990
North Dakota,86.703704,340.629630,365.740741,379.592593,404.925926,413.703704,2.491078e+04,52.018519,55.296296,224.222222,...,1.403685,3.531502,3.955410,10.178562,17.685400,16.293701,5.143137,7.717923,38,49.814815
Ohio,782.224719,3099.662921,3094.224719,3125.662921,3127.101124,3143.460674,2.592473e+05,87.011236,594.696629,2487.820225,...,1.130594,1.343825,1.418471,-1.953373,-3.731664,-2.004723,-1.516972,-2.221428,39,49.887640
Oklahoma,337.025641,1347.564103,1342.333333,1367.794872,1373.000000,1383.743590,9.618849e+04,76.012821,209.589744,965.102564,...,1.267738,2.062214,1.966682,1.167865,-0.190687,2.586180,-0.491743,-0.441090,40,49.871795
Oregon,642.000000,2453.783784,2427.621622,2432.702703,2465.027027,2491.405405,2.070851e+05,35.027027,420.216216,1758.756757,...,0.782994,1.147373,1.154022,0.777475,0.376182,0.554408,2.838808,6.558683,41,49.729730
Pennsylvania,1061.794118,4204.617647,4179.882353,4171.411765,4162.029412,4175.176471,3.735994e+05,66.014706,886.235294,3757.794118,...,-0.716604,-0.506350,-0.505196,0.603322,-0.251711,-1.792030,-1.163071,-1.847809,42,49.852941
Rhode Island,958.333333,3668.000000,3670.000000,3623.333333,3609.000000,3661.333333,3.508557e+05,4.166667,778.333333,3254.333333,...,-0.170788,-0.484658,-0.230390,-3.775228,-1.048551,-0.204570,1.137026,0.723810,44,48.333333
South Carolina,603.404255,2445.617021,2447.744681,2407.404255,2444.595745,2464.042553,1.968240e+05,45.021277,412.085106,1788.595745,...,0.659936,0.850789,0.678485,-1.472263,-0.306189,1.327016,3.492896,2.782227,45,49.787234
South Dakota,90.507463,351.850746,354.955224,359.611940,371.134328,368.477612,2.430388e+04,66.940299,57.552239,217.701493,...,2.666053,5.298887,5.033705,1.911915,1.439128,0.736253,-5.302795,-4.119402,46,49.850746
Tennessee,409.645833,1637.833333,1673.020833,1672.291667,1673.958333,1692.937500,1.322105e+05,94.010417,298.229167,1254.187500,...,-0.600753,-0.350063,0.003528,1.126826,2.052995,2.309163,4.114514,3.222675,47,49.895833
Texas,727.584314,2994.086275,2965.662745,3015.003922,3081.513725,3122.258824,1.972201e+05,253.003922,320.721569,1318.086275,...,2.307281,3.652447,3.961225,0.596987,-0.318782,2.231198,0.294187,5.312238,48,49.960784
Utah,916.800000,3461.000000,3363.066667,3457.200000,3396.066667,3434.400000,1.842590e+05,28.033333,246.400000,1000.133333,...,8.617214,8.809143,9.165748,0.118982,-5.076607,2.873422,-0.323116,3.945287,49,49.666667
Vermont,220.533333,806.933333,812.266667,796.266667,795.333333,797.466667,8.343213e+04,13.066667,177.200000,724.133333,...,0.067339,0.211974,0.507417,0.173740,-2.423507,0.078297,-1.853272,-2.161046,50,49.333333
Virginia,383.850746,1527.268657,1533.820896,1529.791045,1534.104478,1542.641791,1.193718e+05,262.022388,219.149254,902.089552,...,0.403384,1.167868,1.056480,1.425543,1.554178,2.106060,1.113487,1.428749,51,49.925373
Washington,1112.200000,4335.150000,4335.700000,4362.200000,4374.550000,4439.100000,3.362270e+05,38.025000,591.500000,2491.700000,...,2.532388,2.412320,2.524687,4.071678,1.142338,1.740031,3.845933,7.155971,53,49.750000
West Virginia,182.285714,730.785714,738.500000,747.642857,739.464286,741.571429,6.617836e+04,54.017857,186.964286,782.500000,...,-1.514972,-1.185371,-1.212872,0.165489,-0.709094,-1.979607,-3.144217,-2.635547,54,49.821429
Wisconsin,481.041096,1857.315068,1853.287671,1832.602740,1825.424658,1831.753425,1.558078e+05,70.123288,321.780822,1328.438356,...,0.675113,1.047348,1.211926,0.336399,-3.125900,-0.289083,-0.544351,-1.739969,55,49.863014
Wyoming,166.250000,622.583333,619.500000,625.750000,646.500000,641.250000,4.696883e+04,22.041667,107.750000,370.583333,...,3.599852,4.587221,4.167062,-1.468521,5.328961,4.388464,-4.710593,-1.858504,56,49.583333

In [20]:
pd.pivot_table(df,index='STNAME',
              values = 'BIRTHS2010')

                       BIRTHS2010
STNAME
Alabama                418.411765
Alaska                 192.800000
Arizona               2617.125000
Arkansas               248.394737
California            4180.474576
Colorado               516.646154
Connecticut           2108.666667
Delaware              1423.500000
District of Columbia  2243.000000
Florida               1496.235294
Georgia                406.112500
Hawaii                1548.666667
Idaho                  265.377778
Illinois               812.349515
Indiana                450.774194
Iowa                   199.340000
Kansas                 188.528302
Kentucky               226.297521
Louisiana              448.400000
Maine                  405.058824
Maryland              1476.880000
Massachusetts         2486.266667
Michigan               692.904762
Minnesota              397.727273
Mississippi            227.012048
Missouri               327.793103
Montana                107.649123
Nebraska               138.617021
Nevada                 988.000000
New Hampshire          594.363636
New Jersey            2411.727273
New Mexico             391.117647
New York              1949.650794
North Carolina         592.356436
North Dakota            86.703704
Ohio                   782.224719
Oklahoma               337.025641
Oregon                 642.000000
Pennsylvania          1061.794118
Rhode Island           958.333333
South Carolina         603.404255
South Dakota            90.507463
Tennessee              409.645833
Texas                  727.584314
Utah                   916.800000
Vermont                220.533333
Virginia               383.850746
Washington            1112.200000
West Virginia          182.285714
Wisconsin              481.041096
Wyoming                166.250000

In [21]:
pd.pivot_table(df,index='STNAME',
              values = 'BIRTHS2010',
              aggfunc = 'sum')

                      BIRTHS2010
STNAME
Alabama                    28452
Alaska                      5784
Arizona                    41874
Arkansas                   18878
California                246648
Colorado                   33582
Connecticut                18978
Delaware                    5694
District of Columbia        4486
Florida                   101744
Georgia                    64978
Hawaii                      9292
Idaho                      11942
Illinois                   83672
Indiana                    41922
Iowa                       19934
Kansas                     19984
Kentucky                   27382
Louisiana                  29146
Maine                       6886
Maryland                   36922
Massachusetts              37294
Michigan                   58204
Minnesota                  35000
Mississippi                18842
Missouri                   38024
Montana                     6136
Nebraska                   13030
Nevada                     17784
New Hampshire               6538
New Jersey                 53058
New Mexico                 13298
New York                  122828
North Carolina             59828
North Dakota                4682
Ohio                       69618
Oklahoma                   26288
Oregon                     23754
Pennsylvania               72202
Rhode Island                5750
South Carolina             28360
South Dakota                6064
Tennessee                  39326
Texas                     185534
Utah                       27504
Vermont                     3308
Virginia                   51436
Washington                 44488
West Virginia              10208
Wisconsin                  35116
Wyoming                     3990

In [23]:
pd.pivot_table(df,index='STNAME',
              values = 'BIRTHS2010',
              aggfunc = ['sum','median','mean'])

                            sum     median         mean
                     BIRTHS2010 BIRTHS2010   BIRTHS2010
STNAME
Alabama                   28452      111.0   418.411765
Alaska                     5784       24.5   192.800000
Arizona                   41874      440.5  2617.125000
Arkansas                  18878       54.5   248.394737
California               246648      574.0  4180.474576
Colorado                  33582       38.0   516.646154
Connecticut               18978      656.0  2108.666667
Delaware                   5694     1139.0  1423.500000
District of Columbia       4486     2243.0  2243.000000
Florida                  101744      235.0  1496.235294
Georgia                   64978       64.5   406.112500
Hawaii                     9292      535.0  1548.666667
Idaho                     11942       48.0   265.377778
Illinois                  83672       69.0   812.349515
Indiana                   41922      106.0   450.774194
Iowa                      19934       47.0   199.340000
Kansas                    19984       21.0   188.528302
Kentucky                  27382       56.0   226.297521
Louisiana                 29146      102.0   448.400000
Maine                      6886      132.0   405.058824
Maryland                  36922      364.0  1476.880000
Massachusetts             37294     1328.0  2486.266667
Michigan                  58204      109.5   692.904762
Minnesota                 35000       68.5   397.727273
Mississippi               18842       77.0   227.012048
Missouri                  38024       52.5   327.793103
Montana                    6136       18.0   107.649123
Nebraska                  13030       19.5   138.617021
Nevada                    17784       65.5   988.000000
New Hampshire              6538      186.0   594.363636
New Jersey                53058     1227.0  2411.727273
New Mexico                13298       88.0   391.117647
New York                 122828      248.0  1949.650794
North Carolina            59828      147.0   592.356436
North Dakota               4682       10.0    86.703704
Ohio                      69618      163.0   782.224719
Oklahoma                  26288       68.5   337.025641
Oregon                    23754      126.0   642.000000
Pennsylvania              72202      231.0  1061.794118
Rhode Island               5750      322.5   958.333333
South Carolina            28360      184.0   603.404255
South Dakota               6064       17.0    90.507463
Tennessee                 39326       87.0   409.645833
Texas                    185534       53.0   727.584314
Utah                      27504       83.5   916.800000
Vermont                    3308      101.0   220.533333
Virginia                  51436       68.0   383.850746
Washington                44488      164.0  1112.200000
West Virginia             10208       64.5   182.285714
Wisconsin                 35116      120.0   481.041096
Wyoming                    3990       65.0   166.250000

In [24]:
pd.pivot_table(df,index='STNAME',
              values = ['BIRTHS2010', 'BIRTHS2012'],
              aggfunc = ['sum','median','mean'])

                            sum                median                    mean  \
                     BIRTHS2010 BIRTHS2012 BIRTHS2010 BIRTHS2012   BIRTHS2010
STNAME
Alabama                   28452     118124      111.0      412.0   418.411765
Alaska                     5784      22252       24.5      111.0   192.800000
Arizona                   41874     171132      440.5     1705.0  2617.125000
Arkansas                  18878      77208       54.5      249.0   248.394737
California               246648     994862      574.0     2375.0  4180.474576
Colorado                  33582     129480       38.0      150.0   516.646154
Connecticut               18978      73698      656.0     2866.0  2108.666667
Delaware                   5694      22316     1139.0     4492.5  1423.500000
District of Columbia       4486      18468     2243.0     9234.0  2243.000000
Florida                  101744     428072      235.0      948.5  1496.235294
Georgia                   64978     263774       64.5      281.5   406.112500
Hawaii                     9292      37782      535.0     2248.5  1548.666667
Idaho                     11942      44728       48.0      198.0   265.377778
Illinois                  83672     320280       69.0      293.0   812.349515
Indiana                   41922     166120      106.0      411.0   450.774194
Iowa                      19934      76942       47.0      172.0   199.340000
Kansas                    19984      79180       21.0       85.0   188.528302
Kentucky                  27382     110596       56.0      236.0   226.297521
Louisiana                 29146     124526      102.0      506.0   448.400000
Maine                      6886      25602      132.0      496.0   405.058824
Maryland                  36922     145424      364.0     1391.0  1476.880000
Massachusetts             37294     144416     1328.0     5426.0  2486.266667
Michigan                  58204     226160      109.5      401.0   692.904762
Minnesota                 35000     136118       68.5      289.0   397.727273
Mississippi               18842      78842       77.0      310.0   227.012048
Missouri                  38024     150858       52.5      223.0   327.793103
Montana                    6136      24074       18.0       72.0   107.649123
Nebraska                  13030      51532       19.5       73.0   138.617021
Nevada                    17784      69418       65.5      300.0   988.000000
New Hampshire              6538      24738      186.0      796.0   594.363636
New Jersey                53058     209032     1227.0     4641.0  2411.727273
New Mexico                13298      54076       88.0      331.0   391.117647
New York                 122828     479846      248.0      933.0  1949.650794
North Carolina            59828     239134      147.0      602.0   592.356436
North Dakota               4682      19750       10.0       44.5    86.703704
Ohio                      69618     275386      163.0      630.0   782.224719
Oklahoma                  26288     104702       68.5      331.5   337.025641
Oregon                    23754      89822      126.0      428.0   642.000000
Pennsylvania              72202     284232      231.0      925.0  1061.794118
Rhode Island               5750      22020      322.5     1272.5   958.333333
South Carolina            28360     115044      184.0      696.0   603.404255
South Dakota               6064      23782       17.0       68.0    90.507463
Tennessee                 39326     160610       87.0      344.0   409.645833
Texas                    185534     756244       53.0      217.0   727.584314
Utah                      27504     100892       83.5      357.5   916.800000
Vermont                    3308      12184      101.0      327.0   220.533333
Virginia                  51436     205532       68.0      272.5   383.850746
Washington                44488     173428      164.0      670.0  1112.200000
West Virginia             10208      41356       64.5      271.5   182.285714
Wisconsin                 35116     135290      120.0      419.0   481.041096
Wyoming                    3990      14868       65.0      212.0   166.250000


                        BIRTHS2012
STNAME
Alabama                1737.117647
Alaska                  741.733333
Arizona               10695.750000
Arkansas               1015.894737
California            16862.067797
Colorado               1992.000000
Connecticut            8188.666667
Delaware               5579.000000
District of Columbia   9234.000000
Florida                6295.176471
Georgia                1648.587500
Hawaii                 6297.000000
Idaho                   993.955556
Illinois               3109.514563
Indiana                1786.236559
Iowa                    769.420000
Kansas                  746.981132
Kentucky                914.016529
Louisiana              1915.784615
Maine                  1506.000000
Maryland               5816.960000
Massachusetts          9627.733333
Michigan               2692.380952
Minnesota              1546.795455
Mississippi             949.903614
Missouri               1300.500000
Montana                 422.350877
Nebraska                548.212766
Nevada                 3856.555556
New Hampshire          2248.909091
New Jersey             9501.454545
New Mexico             1590.470588
New York               7616.603175
North Carolina         2367.663366
North Dakota            365.740741
Ohio                   3094.224719
Oklahoma               1342.333333
Oregon                 2427.621622
Pennsylvania           4179.882353
Rhode Island           3670.000000
South Carolina         2447.744681
South Dakota            354.955224
Tennessee              1673.020833
Texas                  2965.662745
Utah                   3363.066667
Vermont                 812.266667
Virginia               1533.820896
Washington             4335.700000
West Virginia           738.500000
Wisconsin              1853.287671
Wyoming                 619.500000

In [25]:
df

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43593,...,1.072643,16.243199,-5.339774,-14.252889,-14.248864,1.255221,16.243199,-5.295460,-14.075283,-14.070195
3189,50,4,8,56,39,Wyoming,Teton County,21294,21294,21297,...,-1.589565,0.972695,19.525929,14.143021,-0.564849,0.654527,2.408578,21.160658,16.308671,1.520747
3190,50,4,8,56,41,Wyoming,Uinta County,21118,21118,21102,...,-17.755986,-4.916350,-6.902954,-14.215862,-12.127022,-18.136812,-5.536861,-7.521840,-14.740608,-12.606351
3191,50,4,8,56,43,Wyoming,Washakie County,8533,8533,8545,...,-11.637475,-0.827815,-2.013502,-17.781491,1.682288,-11.990126,-1.182592,-2.250385,-18.020168,1.441961
3192,50,4,8,56,45,Wyoming,Weston County,7208,7208,7181,...,-11.752361,-8.040059,12.372583,1.533635,6.935294,-12.032179,-8.040059,12.372583,1.533635,6.935294

In [27]:
pd.pivot_table(df,index='CTYNAME',
              values = 'BIRTHS2010',
              aggfunc = ['sum','median','mean'])

                                 sum     median       mean
                          BIRTHS2010 BIRTHS2010 BIRTHS2010
CTYNAME
Abbeville County                  64       64.0      64.00
Acadia Parish                    211      211.0     211.00
Accomack County                   87       87.0      87.00
Ada County                      1307     1307.0    1307.00
Adair County                     181       51.5      45.25
...                              ...        ...        ...
Yukon-Koyukuk Census Area         21       21.0      21.00
Yuma County                      745      372.5     372.50
Zapata County                     91       91.0      91.00
Zavala County                     36       36.0      36.00
Ziebach County                    15       15.0      15.00

[1927 rows x 3 columns]

In [28]:
pd.pivot_table(df,index=['STNAME', 'CTYNAME'],
              values = 'BIRTHS2010',
              aggfunc = ['sum','median','mean'])

                               sum     median       mean
                        BIRTHS2010 BIRTHS2010 BIRTHS2010
STNAME  CTYNAME
Alabama Alabama              14226      14226      14226
        Autauga County         151        151        151
        Baldwin County         517        517        517
        Barbour County          70         70         70
        Bibb County             44         44         44
...                            ...        ...        ...
Wyoming Teton County            76         76         76
        Uinta County            73         73         73
        Washakie County         26         26         26
        Weston County           26         26         26
        Wyoming               1995       1995       1995

[3192 rows x 3 columns]

In [32]:
df2 = pd.read_csv('datasets/airline_data.csv',
                 low_memory=False)
df.head(2)

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333

In [36]:
cols=df2.columns.tolist()
cols.sort()
cols

['ActualElapsedTime',
 'AirTime',
 'ArrDel15',
 'ArrDelay',
 'ArrDelayMinutes',
 'ArrTime',
 'ArrTimeBlk',
 'ArrivalDelayGroups',
 'CRSArrTime',
 'CRSDepTime',
 'CRSElapsedTime',
 'CancellationCode',
 'Cancelled',
 'CarrierDelay',
 'DOT_ID_Reporting_Airline',
 'DayOfWeek',
 'DayofMonth',
 'DepDel15',
 'DepDelay',
 'DepDelayMinutes',
 'DepTime',
 'DepTimeBlk',
 'DepartureDelayGroups',
 'Dest',
 'DestAirportID',
 'DestAirportSeqID',
 'DestCityMarketID',
 'DestCityName',
 'DestState',
 'DestStateFips',
 'DestStateName',
 'DestWac',
 'Distance',
 'DistanceGroup',
 'Div1Airport',
 'Div1AirportID',
 'Div1AirportSeqID',
 'Div1LongestGTime',
 'Div1TailNum',
 'Div1TotalGTime',
 'Div1WheelsOff',
 'Div1WheelsOn',
 'Div2Airport',
 'Div2AirportID',
 'Div2AirportSeqID',
 'Div2LongestGTime',
 'Div2TailNum',
 'Div2TotalGTime',
 'Div2WheelsOff',
 'Div2WheelsOn',
 'Div3Airport',
 'Div3AirportID',
 'Div3AirportSeqID',
 'Div3LongestGTime',
 'Div3TailNum',
 'Div3TotalGTime',
 'Div3WheelsOff',
 'Div3WheelsOn',
 'Div4Airport',
 'Div4AirportID',
 'Div4AirportSeqID',
 'Div4LongestGTime',
 'Div4TailNum',
 'Div4TotalGTime',
 'Div4WheelsOff',
 'Div4WheelsOn',
 'Div5Airport',
 'Div5AirportID',
 'Div5AirportSeqID',
 'Div5LongestGTime',
 'Div5TailNum',
 'Div5TotalGTime',
 'Div5WheelsOff',
 'Div5WheelsOn',
 'DivActualElapsedTime',
 'DivAirportLandings',
 'DivArrDelay',
 'DivDistance',
 'DivReachedDest',
 'Diverted',
 'FirstDepTime',
 'FlightDate',
 'Flight_Number_Reporting_Airline',
 'Flights',
 'IATA_CODE_Reporting_Airline',
 'LateAircraftDelay',
 'LongestAddGTime',
 'Month',
 'NASDelay',
 'Origin',
 'OriginAirportID',
 'OriginAirportSeqID',
 'OriginCityMarketID',
 'OriginCityName',
 'OriginState',
 'OriginStateFips',
 'OriginStateName',
 'OriginWac',
 'Quarter',
 'Reporting_Airline',
 'SecurityDelay',
 'Tail_Number',
 'TaxiIn',
 'TaxiOut',
 'TotalAddGTime',
 'Unnamed: 0',
 'WeatherDelay',
 'WheelsOff',
 'WheelsOn',
 'Year']

In [41]:
pd.pivot_table(df2,
               index=['Year', 'Quarter'],
              values = 'DepDelay',
              columns= 'DepartureDelayGroups',
              margins=True,
              aggfunc='sum')

DepartureDelayGroups   -2.0     -1.0      0.0      1.0      2.0      3.0  \
Year Quarter
1987 4                  NaN    -20.0     81.0    145.0     36.0     97.0
1988 1                  NaN    -15.0    121.0    131.0      NaN     97.0
     2                  NaN    -11.0     84.0    119.0    105.0     52.0
     3                  NaN    -23.0     89.0     21.0     39.0      NaN
     4                  NaN    -15.0     91.0    137.0    119.0      NaN
...                     ...      ...      ...      ...      ...      ...
2019 2                -19.0   -326.0    117.0    208.0    185.0    162.0
     3                  NaN   -254.0     88.0     67.0    197.0     53.0
     4                  NaN   -236.0     92.0    133.0    176.0     47.0
2020 1                  NaN   -314.0     54.0     44.0    108.0     57.0
All                  -226.0 -17336.0  11373.0  13688.0  11974.0  10061.0

DepartureDelayGroups     4.0     5.0     6.0     7.0     8.0     9.0    10.0  \
Year Quarter
1987 4                   NaN     NaN     NaN     NaN     NaN     NaN     NaN
1988 1                  63.0    82.0    98.0   109.0     NaN     NaN     NaN
     2                   NaN    78.0     NaN     NaN     NaN     NaN   151.0
     3                   NaN     NaN     NaN     NaN     NaN     NaN     NaN
     4                  63.0    85.0     NaN     NaN     NaN     NaN     NaN
...                      ...     ...     ...     ...     ...     ...     ...
2019 2                 193.0   169.0   103.0   115.0   131.0     NaN   164.0
     3                 131.0   150.0    97.0     NaN     NaN     NaN     NaN
     4                  70.0     NaN     NaN     NaN     NaN     NaN     NaN
2020 1                 135.0    83.0     NaN     NaN     NaN   140.0     NaN
All                   9031.0  6542.0  5436.0  4723.0  3262.0  2999.0  3748.0

DepartureDelayGroups    11.0     12.0      All
Year Quarter
1987 4                   NaN      NaN    339.0
1988 1                   NaN      NaN    686.0
     2                 179.0      NaN    757.0
     3                   NaN      NaN    126.0
     4                   NaN      NaN    480.0
...                      ...      ...      ...
2019 2                   NaN      NaN   1202.0
     3                   NaN    522.0   1051.0
     4                   NaN      NaN    282.0
2020 1                   NaN      NaN    307.0
All                   2399.0  12933.0  80607.0

[131 rows x 16 columns]

In [42]:
#lambda arguments : expression
x = lambda a:a+2
x(5)

7

In [43]:
x = lambda a=0,b=0,c=0 : a+b+c
x(2,3,4)

9

In [46]:
full_name = lambda first, last: f'Full name: {first.title()} {last.title()}'
full_name ('juan', 'carlos')

'Full name: Juan Carlos'

In [49]:
df= pd.DataFrame(['A+','A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D', 'D-'],
                index = ['Excellent', 'Excellent', 'Excellent', 'Good', 'Good', 'Good', 'ok', 'ok', 'ok', 'poor', 'poor', 'poor'],
                columns = ['Grades'])
df

          Grades
Excellent     A+
Excellent      A
Excellent     A-
Good          B+
Good           B
Good          B-
ok            C+
ok             C
ok            C-
poor          D+
poor           D
poor          D-

In [51]:
df.dtypes

Grades    object
dtype: object

In [52]:
df['Grades']

Excellent    A+
Excellent     A
Excellent    A-
Good         B+
Good          B
Good         B-
ok           C+
ok            C
ok           C-
poor         D+
poor          D
poor         D-
Name: Grades, dtype: object

In [58]:
df['Grades'].astype('category')
my_category = pd.CategoricalDtype(
              categories = ['A+','A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D', 'D-'],
    ordered=True
    
)
grades = df['Grades'].astype(my_category)
grades

Excellent    A+
Excellent     A
Excellent    A-
Good         B+
Good          B
Good         B-
ok           C+
ok            C
ok           C-
poor         D+
poor          D
poor         D-
Name: Grades, dtype: category
Categories (12, object): [A+ < A < A- < B+ ... C- < D+ < D < D-]

In [61]:
df3 = pd.read_csv('datasets/cwurData.csv')
df3.head(2)

,world_rank,institution,country,national_rank,quality_of_education,alumni_employment,quality_of_faculty,publications,influence,citations,broad_impact,patents,score,year
0,1,Harvard University,USA,1,7,9,1,1,1,1,NaN,5,100.00,2012
1,2,Massachusetts Institute of Technology,USA,2,9,17,3,12,4,4,NaN,1,91.67,2012

In [65]:
def create_category(ranking): 
    if(ranking >=1)&(ranking<=100):
       return 'First tier university'
    elif(ranking >=100)&(ranking<=200):
       return 'Second tier university'
    elif(ranking >=200)&(ranking<=300):
       return 'Third tier university'
    else:
       return 'Other top university'

In [66]:
df3['Rank_level'] = df3['world_rank'].apply(lambda x:create_category(x))

In [68]:
df3

,world_rank,institution,country,national_rank,quality_of_education,alumni_employment,quality_of_faculty,publications,influence,citations,broad_impact,patents,score,year,Rank_level
0,1,Harvard University,USA,1,7,9,1,1,1,1,NaN,5,100.00,2012,First tier university
1,2,Massachusetts Institute of Technology,USA,2,9,17,3,12,4,4,NaN,1,91.67,2012,First tier university
2,3,Stanford University,USA,3,17,11,5,4,2,2,NaN,15,89.50,2012,First tier university
3,4,University of Cambridge,United Kingdom,1,10,24,4,16,16,11,NaN,50,86.17,2012,First tier university
4,5,California Institute of Technology,USA,4,2,29,7,37,22,22,NaN,18,85.21,2012,First tier university
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2195,996,University of the Algarve,Portugal,7,367,567,218,926,845,812,969.0,816,44.03,2015,Other top university
2196,997,Alexandria University,Egypt,4,236,566,218,997,908,645,981.0,871,44.03,2015,Other top university
2197,998,Federal University of Ceará,Brazil,18,367,549,218,830,823,812,975.0,824,44.03,2015,Other top university
2198,999,University of A Coruña,Spain,40,367,567,218,886,974,812,975.0,651,44.02,2015,Other top university
2199,1000,China Pharmaceutical University,China,83,367,567,218,861,991,812,981.0,547,44.02,2015,Other top university